//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Id { get; set; }
        public System.DateTime Date1 { get; set; }
        public int Period { get; set; }
        public int Student_id { get; set; }
        public int Att_type { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
