//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dnevnik.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id { get; set; }
        public int Student_id { get; set; }
        public int Subject_id { get; set; }
        public int Grade_month { get; set; }
        public int Grade1 { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Student Student { get; set; }
    }
}
